### ISSUE TITLE
Does not work for getdisplayMedia

### ISSUE THREAD

**Issue by rohit-raj111** [Choi-Heesu/mediaRecorder-dataChannel-mediaSource#1]
@heesu0 
Hi,
This code works perfectly for getUserMedia.
When I tried to replace getUserMedia API with getDisplayMedia API then remote stream just stucks on the first frame.
I'm new to WebRTC.
Kindly let me know how it can work with getDisplayMedia API.
Thanks.

**Comment by heesu0** [comment]
Hi. It's been a while since I created this project, so I don't remember all the details.

But I checked the issue you mentioned and avoided it in the following way, although I don't know the exact cause.

```diff
diff --git a/js/main.js b/js/main.js
index 348c8ad..1d68c84 100644
--- a/js/main.js
+++ b/js/main.js
@@ -118,8 +118,8 @@ function sendMessage(message) {
  * Media part (getUserMedia, mediaSource)
  ******************************************************/
 
-navigator.mediaDevices.getUserMedia({
-    audio: true,
+navigator.mediaDevices.getDisplayMedia({
+    audio: false,
     video: true
 })
 .then(gotStream)
@@ -137,7 +137,7 @@ let isMediaInit = false;
 
 mediaSource.addEventListener('sourceopen', function (e) {
     //const mimeCodec = 'video/mp4; codecs="avc1.42E01E, opus"';
-    const mimeCodec = 'video/webm; codecs="vp8, opus"';
+    const mimeCodec = 'video/webm; codecs="vp8"';
     sourceBuffer = mediaSource.addSourceBuffer(mimeCodec);
     sourceBuffer.mode = 'segments'; // 
     sourceBuffer.addEventListener('updateend', function () {
@@ -301,7 +301,7 @@ function toggleStreaming() {
 
 function startStreaming() {
     // let options = { mimeType: 'video/webm; codecs="h264, opus"' };
-    let options = { mimeType: 'video/webm; codecs="vp8, opus"' };
+    let options = { mimeType: 'video/webm; codecs="vp8"' };
     try {
         mediaRecorder = new MediaRecorder(window.stream, options);
     } catch (e0) {
```

It looks like MediaRecorder-MediaSource doesn't work properly if the MediaStream you get with getDisplayMedia API has both video and audio tracks. (It's also possible that the reason why the getUserMedia API worked correctly was because it didn't get the audio track)

**Comment by rohit-raj111** [comment]
Thank you @heesu0 for your quick response. Its working fine without audio track.
Is there a way we can stream audio track as well through datachannel using MSE?

**Comment by heesu0** [comment]
If you use the GetDisplayMedia API to capture a screen with continuous music playing, you'll see that the screen doesn't stop at the first frame. (Sometimes the screen freezes in the middle)

It seems that the way the MediaRecorder records silence may not be properly handled by MSE. To understand further, we need to figure out the internal behavior of MSE. I'm afraid I can't assist you with that, sorry :(
